# Consultas
SELECT * FROM PRODUCT;

SELECT * FROM CLIENTS;

SELECT * FROM SUPPLIER;

SELECT * FROM SELLER;

SELECT * FROM ORDERS;

SELECT * FROM PAYMENTS;

SELECT * FROM STORAGES;

# Quantos Produtos?
SELECT COUNT(*) AS N_PRODUTOS FROM PRODUCT;

# Quantos Clientes?
SELECT COUNT(*) AS N_CLIENTES FROM CLIENTS;

# Quantos Fornecedores?
SELECT COUNT(*) AS N_FORNECEDORES FROM SUPPLIER;

# Quantos Vendedores?
SELECT COUNT(*) AS N_VENDEDORES FROM SELLER;

# Quantos pedidos?
SELECT COUNT(*) AS N_PEDIDOS FROM ORDERS;

# Quantos pedidos tiveram para o produto Relógio Digital Ben 10?
SELECT COUNT(*) AS N_PEDIDOS_RELOGIO 
FROM PRODUCT A
INNER JOIN PRODUCTORDER B ON A.IDPRODUCT = B.IDPOPRODUCT
WHERE A.PNAME LIKE '%RELÓGIO%BEN%10%';

# O histórico da compra nº 5
SELECT 
B.FNAME, 
B.MINIT, 
B.LNAME, 
B.CPF, 
B.ADDRESS, 
A.ORDERSTATUS, 
A.SENDVALUE, 
A.PAYMENTCASH,
D.PNAME,
F.LOCALSTORAGE
FROM ORDERS A
INNER JOIN CLIENTS B ON A.IDORDERCLIENT = B.IDCLIENT
INNER JOIN PRODUCTORDER C ON A.IDORDER = C.IDPOORDER
INNER JOIN PRODUCT D ON C.IDPOPRODUCT = D.IDPRODUCT
INNER JOIN PRODUCTSTORAGE E ON D.IDPRODUCT = E.IDPSPRODUCT
INNER JOIN STORAGES F ON E.IDPSSTORAGE = F.IDSTORAGE
WHERE A.IDORDER = 5;

# Nome completo dos clientes que compraram Fone de ouvido.
SELECT CONCAT(FNAME, ' ', MINIT, ' ', LNAME) AS NOME_COMPLETO
FROM PRODUCT A
INNER JOIN PRODUCTORDER B ON A.IDPRODUCT = B.IDPOPRODUCT
INNER JOIN ORDERS C ON C.IDORDER = B.IDPOORDER
INNER JOIN CLIENTS D ON D.IDCLIENT = C.IDORDERCLIENT
WHERE PNAME LIKE '%FONE%OUVIDO%'
ORDER BY 1;

# Excluir pedidos 2 e 6
DELETE FROM PAYMENTS WHERE IDORDER IN (2, 6);
DELETE FROM PRODUCTORDER WHERE idPOOrder IN (2, 6);
DELETE FROM ORDERS WHERE IDORDER IN (2, 6);
SELECT * FROM ORDERS;
 
# Mudar nome Ricardo para João
UPDATE CLIENTS SET FNAME = 'João' WHERE FNAME = 'Matheus';
SELECT * FROM CLIENTS;

# Quantas vendas cada vendedor teve?
SELECT E.SOCIALNAME AS VENDEDOR, COUNT(*) AS N_PEDIDOS_VENDIDOS
FROM ORDERS A 
INNER JOIN PRODUCTORDER B ON A.IDORDER = B.IDPOORDER
INNER JOIN PRODUCT C ON B.IDPOPRODUCT = C.IDPRODUCT
INNER JOIN PRODUCTSELLER D ON D.IDPSPRODUCT = C.IDPRODUCT
INNER JOIN SELLER E ON D.IDPSSELLER = E.IDSELLER
GROUP BY E.SOCIALNAME;

# Quantas vendas o vendedor Alessandro teve?
SELECT E.SOCIALNAME AS VENDEDOR, COUNT(*) AS N_PEDIDOS_VENDIDOS
FROM ORDERS A 
INNER JOIN PRODUCTORDER B ON A.IDORDER = B.IDPOORDER
INNER JOIN PRODUCT C ON B.IDPOPRODUCT = C.IDPRODUCT
INNER JOIN PRODUCTSELLER D ON D.IDPSPRODUCT = C.IDPRODUCT
INNER JOIN SELLER E ON D.IDPSSELLER = E.IDSELLER
GROUP BY E.SOCIALNAME
HAVING E.SOCIALNAME LIKE 'ALESSANDRO%';

